[package]
name = "editor"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [ "Window", "Document", "HtmlElement", "console" ] }

[lib]
crate-type = ["cdylib", "rlib"]
